### ISSUE TITLE
Specific artwork causes app to crash on magicNumberData

### ISSUE THREAD

**Issue by Dreeke** [NCrusher74/SwiftTagger#4]
Hi @NCrusher74,

I love this package! I'm running into the following issue though:

When I import a specific mp3 file my app crashes on Swifttagger in ImageFormat.swift line 93.

The mp3 is a downloaded podcast: https://chtbl.com/track/91854/traffic.megaphone.fm/LAV1308607275.mp3?updated=1626721464

The culprit appears to be the artwork.

It crashes on the line 93 that is linked to .bmp even though the actual image appears to be a .tiff format.

```
 } else if magicNumberData[0..<2] == Data([0x42, 0x4D]) {
            self = .bmp
        } else if magicNumberData[0..<3] == Data([0x49, 0x20, 0x49]) {
            self = .tiff
```

A screenshot is attached with the hex codes for the beginning of the file. 

<img width="642" alt="Screenshot 2021-08-24 at 12 19 02" src="https://user-images.githubusercontent.com/1224795/130607813-34a68bdf-15a2-4fa2-bfb3-68aebe216d66.png">

When I remove the artwork from the file it imports the mp3 into my app without any issues.

Dreeke

**Comment by NCrusher74** [comment]
Hi @Dreeke . I apologize for the delay in responding, life has prevented me from being able to work on this recently.

The problem was actually in SwiftTaggerID3, so update your dependencies to 1.8.1 and let me know if that solves the problem.

**Comment by Dreeke** [comment]
Perfect! That solves the problem. Thank you for the fix @NCrusher74!
